#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale $HOME/wallpapers/audio-bunny.png
$HOME/.config/polybar/launch.sh
pkill picom
picom --config $HOME/.config/picom/config &
wmname LG3D &

xinput set-prop 12 'libinput Disable While Typing Enabled' 1
xinput set-prop 12 "libinput Natural Scrolling Enabled" 1
xinput set-prop 12 "libinput Tapping Enabled" 1

bspc monitor -d I II III IV V 
bspc monitor HDMI-0 -d I II III

bspc config border_width         2
bspc config window_gap           8

bspc config top_padding          0
bspc config bottom_padding       0
bspc config right_padding 	 4
bspc config left_padding  	 4

bspc config normal_border_color "#13141d"
bspc config active_border_color "#7b68ee"
bspc config focused_border_color "#7b68ee"

bspc config split_ratio          .58
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
